// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtLd3LyBGnVM38dSXLgJBtGwKma6Lqygs',
    appId: '1:912621917226:web:4c9ae368ec728618c69f53',
    messagingSenderId: '912621917226',
    projectId: 'nyangcoach',
    authDomain: 'nyangcoach.firebaseapp.com',
    storageBucket: 'nyangcoach.firebasestorage.app',
    measurementId: 'G-HH6305J2H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9xoVzpI5jLQeUxNdLJSXue7MC0hl-qmM',
    appId: '1:912621917226:android:d8f8876a860616c8c69f53',
    messagingSenderId: '912621917226',
    projectId: 'nyangcoach',
    storageBucket: 'nyangcoach.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7oqj7io7ixjnxba8TWqS1H7rpz-RkikE',
    appId: '1:912621917226:ios:b86b41359211a272c69f53',
    messagingSenderId: '912621917226',
    projectId: 'nyangcoach',
    storageBucket: 'nyangcoach.firebasestorage.app',
    iosClientId:
        '912621917226-ajnj53vsr2q11ikd6osla0aog9e4p2u3.apps.googleusercontent.com',
    iosBundleId: 'com.nyang.nyangCoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7oqj7io7ixjnxba8TWqS1H7rpz-RkikE',
    appId: '1:912621917226:ios:b86b41359211a272c69f53',
    messagingSenderId: '912621917226',
    projectId: 'nyangcoach',
    storageBucket: 'nyangcoach.firebasestorage.app',
    iosClientId:
        '912621917226-ajnj53vsr2q11ikd6osla0aog9e4p2u3.apps.googleusercontent.com',
    iosBundleId: 'com.nyang.nyangCoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtLd3LyBGnVM38dSXLgJBtGwKma6Lqygs',
    appId: '1:912621917226:web:4c9ae368ec728618c69f53',
    messagingSenderId: '912621917226',
    projectId: 'nyangcoach',
    authDomain: 'nyangcoach.firebaseapp.com',
    storageBucket: 'nyangcoach.firebasestorage.app',
    measurementId: 'G-HH6305J2H9',
  );
}
